
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Assignment 1, layout template from Bootstrap">
    <meta name="author" content="101190261/Kurt Chiu, Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Client Notification Manager</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/">

    <!-- Bootstrap core CSS -->
	<link href="style.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
</head>

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <?php echo ($page == 'home'? 'active'  : '');?>">
        <a class="nav-link" href="?page=home">Home</span></a>
      </li>
      <li class="nav-item <?php echo ($page == 'client'? 'active' : '');?>">
        <a class="nav-link" href="?page=client&action=view">Clients</a>
      </li>
	  <li class="nav-item <?php echo ($page == 'notification'? 'active' : '');?>">
        <a class="nav-link" href="?page=notification&action=view">Notifications</a>
      </li>
	  <li class="nav-item <?php echo ($page == 'clientevent'? 'active' : '');?>">
        <a class="nav-link" href="?page=clientevent&action=view">Notifications per Client</a>
      </li>
	  <li class="nav-item <?php echo ($page == 'user'? 'active' : '');?>">
        <a class="nav-link" href="?page=user&action=view">Manage users</a>
      </li>
	  <li class="nav-item <?php echo ($page == 'log'? 'active' : '');?>">
        <a class="nav-link" href="?page=log&action=view">View usage logs</a>
      </li>
	  <li class="nav-item <?php echo ($page == 'db'? 'active' : '');?>">
        <a class="nav-link" href="?page=db&action=view">Database backup/restore</a>
      </li>
	  <li>
		 <a class="nav-link" href="logout.phtml">Log out</a>
	  </li>
    </ul>
  </div>
</nav> <!-- End of navbar -->

<?php include $main_content ?><?php
$source_links [] = "<br><a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source of ". __FILE__;
?>
