<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Database Backup and Restore</h1>  
    </div>
  </div>
  <div class="container">
  <p>
  <table class="table table-hover">
    <?php
		/*$filter = $_GET ['filter'];
		list_headers ($header_items);
		list_itemsDB ($fileinfo,$filter,$page);*/
    ?>
	
	<tr>
		<td>
		Download backup
		</td>
		<td>
			<a href = "?page=db&action=download">Generate File</a>
		</td>
	</tr>
	
	<tr>
		<td>
		Restore database (Duplicate filenames will be overwritten)
		</td>
		<td>
		<form action="?page=db&action=upload" method="post" enctype="multipart/form-data">
			<input type="file" name ="dbfile" accept=".sql">
			<input type="submit" value="Upload">
		</form>	
		</td>
	</tr>
	
	</table>
  <p>
  </div>
</main>


<?php
$source_links [] = "<br><a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source of ". __FILE__;
?>
