<?php if(is_array($row_to_update)):?>
<script src="../app/lib/jsfunc.js"></script>
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><?php echo ucfirst($_GET['action']); ?> a <?php echo ucfirst($page);?></h1>
    </div>
  </div>
	<div class="container">
		
<form <?php echo 'action="?page='.$page.'&action=doUpdate"';?> method="post" enctype="multipart/form-data">

	<input type="hidden" name="ID" value="<?php echo $row_to_update['ID'];?>">
	
	<table class="table table-hover">
		<tr  style="background:lightgrey;">
			<td>
				Rows marked with * are mandatory and require valid input.
			</td>
			<td>
			</td>
		</tr>
			
		<?php	
			print_row ("*First Name","FirstName",$row_to_update['FirstName']);
			print_row ("*Last Name","LastName",$row_to_update['LastName']);
			print_row ("*E-mail Address","E-mail",$row_to_update['E-mail']);
			print_row ("*Cell number","CellNumber",$row_to_update['CellNumber']);
			print_row ("*Position","Position",$row_to_update['Position']);
			print_row ("Username","Username",$row_to_update['Username']);
			
			
			echo
			'<input type="hidden" name="Password" value="'.$row_to_update['Password'].'">';
			
		?>
	
		<!-- Status button change requires javascript for confirmation! -->
		<tr>
			<td>Status: Active </td>
			<td><input type="radio" name="Status" value="Active" id="activebutton" 
			<?php if(stripos(($row_to_update['Status']),'Active')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
		<tr>
			<td>Status: Suspended </td>
			<td><input type="radio" name="Status" value="Suspended" id="archivebutton"
			<?php if(stripos(($row_to_update['Status']),'Suspended')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
		
			<tr>
			<td> Upload a photo: </td>
			<td>
				<input type="file" name ="image" accept="image/*">
			</td>
			</tr>
			
		
	</table>
	<?php write_errors($page,$errorpath); ?>
    <br><input type="submit">
</form>
	</div>
</main>
<?php else:?>
    <h1>Cannot find the <?php echo $page;?></h1>
<?php endif; ?>



<?php
$source_links [] = "<br><a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source of ". __FILE__;
?>




