<?php if(is_array($row_to_update)):?>
<script src="../app/lib/jsfunc.js"></script>
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><?php echo ucfirst($_GET['action']); ?> a <?php echo ucfirst($page);?></h1>
    </div>
  </div>
	<div class="container">
		
<form <?php echo 'action="?page='.$page.'&action=doUpdate"';?> method="post">

	<input type="hidden" name="ID" value="<?php echo $row_to_update['ID'];?>">
	
	<table class="table table-hover">
		<tr  style="background:lightgrey;">
			<td>
				Rows marked with * are mandatory and require valid input.
			</td>
			<td>
			</td>
		</tr>
			
		<?php
			echo
			'<tr>
				<td>*Client ID: </td>
				<td><input type="text" name="ClientID" value="'.$row_to_update['ClientID'].'" readonly ></td>
			</tr>';	
			echo
			'<tr>
				<td>*Notification ID: </td>
				<td><input type="text" name="NotificationID" value="'.$row_to_update['NotificationID'].'" readonly ></td>
			</tr>';
		
			print_row ("*Start date dd-mm-yyyy","StartDate",$row_to_update['StartDate']);
			print_row ("*Frequency","Frequency",$row_to_update['Frequency']);
		?>
	
		<!-- Status button change requires javascript for confirmation! -->
		<tr>
			<td>Status: Active </td>
			<td><input type="radio" name="Status" value="Active" id="activebutton" 
			<?php if(stripos(($row_to_update['Status']),'Active')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
		<tr>
			<td>Status: Archive </td>
			<td><input type="radio" name="Status" value="Archive" id="archivebutton"
			<?php if(stripos(($row_to_update['Status']),'Archive')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
	</table>
	<?php write_errors($page,$errorpath); ?>
    <br><input type="submit">
</form>
	</div>
</main>
<?php else:?>
    <h1>Cannot find the <?php echo $page;?></h1>
<?php endif; ?>

<?php
$source_links [] = "<br><a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source of ". __FILE__;
?>



