<?php if(is_array($row_to_update)):?>
<script src="../app/lib/jsfunc.js"></script>
<main role="main">
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3"><?php echo ucfirst($_GET['action']); ?> a <?php echo ucfirst($page);?></h1>
    </div>
  </div>
	<div class="container">
		
<form <?php echo 'action="?page='.$page.'&action=doUpdate"';?> method="post">

	<input type="hidden" name="ID" value="<?php echo $row_to_update['ID'];?>">
	
	<table class="table table-hover">
		<tr  style="background:lightgrey;">
			<td>
				Rows marked with * are mandatory and require valid input. Updating a clients status will have the same effect on all attatched notifications.
			</td>
			<td>
			</td>
		</tr>
			
		<?php
		print_row ("*Company Name","CompanyName",$row_to_update['CompanyName']);
		print_row ("*Business Phone Pumber","BusinessNumber",$row_to_update['BusinessNumber']);
		print_row ("*First Name","ContactFirstName",$row_to_update['ContactFirstName']);
		print_row ("*Last Name","ContactLastName",$row_to_update['ContactLastName']);
		print_row ("*Phone Number","PhoneNumber",$row_to_update['PhoneNumber']);
		print_row ("*Cell Phone Number","CellNumber",$row_to_update['CellNumber']);
		print_row ("Website","Wesbsite",$row_to_update['Wesbsite']);
		?>
	
		<!-- Status button change requires javascript for confirmation! -->
		<tr>
			<td>Status: Active </td>
			<td><input type="radio" name="Status" value="Active" id="activebutton" 
			<?php if(stripos(($row_to_update['Status']),'Active')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
		<tr>
			<td>Status: Archive </td>
			<td><input type="radio" name="Status" value="Archive" id="archivebutton"
			<?php if(stripos(($row_to_update['Status']),'Archive')!==false){echo ' checked="checked"';}?>
			onclick="return ask()">
			</td>
		</tr>
	</table>
	<?php write_errors($page,$errorpath); ?>
    <br><input type="submit">
</form>
	</div>
</main>
<?php else:?>
    <h1>Cannot find the <?php echo $page;?></h1>
<?php endif; ?>



<?php
$source_links [] = "<br><a href='/folder_view/vs.php?s=" . __FILE__ . "' target='_blank'>View Source of ". __FILE__;
?>




